# Overview
Title of project:
Vaccine Hesitancy for COVID-19


Name of project author(s):
Priyanka gannavarapu

Name of project reviewer:
Zhihan Xian

# Specific project content evaluation
Evaluate the different parts of the project by filling in the sections below.

## Background, Context and Motivation
How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?

### Feedback and Comments
The author provides some decent background information regarding covid-19 situation and vaccination. She includes some related work. The project is well placed into the context of existing work. It is clear why the project was undertaken and what new information it hopes to provide. However, it is better to turn those bullet points into a paragraph. 

### Summary assessment (PICK ONE, DELETE THE OTHERS)
* some contextualization and motivation
## Question description
How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?

### Feedback and Comments
The author has a clear question to address. It is clear the questions she asks relate to the data she has.

### Summary assessment
* question/hypotheses somewhat explained

## Data description
How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is? 

### Feedback and Comments
The data is well described and the source is also clear.

### Summary assessment
* source and overall structure of data well explained

## Data wrangling and exploratory analysis
How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments
The author needs more words explaning the exploratory process instead of simply putting the resulting plots there. No alternatives discussed or considered. There are meaningful exploratory results shown but it is in an rmd rundown file. It is better to have a word file for supplementary materials.

### Summary assessment
* some weaknesses in wrangling and exploratory component

## Appropriateness of Analysis
Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments
The author's analysis details are not shown yet at this stage.

### Summary assessment
* inadequate analysis

## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

### Feedback and Comments
There is too little result present so far.

### Summary assessment
* results not finish yet

## Discussion/Conclusions
Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?
### Feedback and Comments
Discussion part is decent with some literature cited and discussed.
### Summary assessment
* minor parts wrong, missing or unclear

## Further comments
_Add any other comments regarding the different aspects of the project here. Write anything you think can help your classmate improve their project._
# Overall project content evaluation
Evaluate overall features of the project  by filling in the sections below.

## Structure
Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments
The project has not finished yet. Supplementary material should probably be written in a word file and placed along with the manuscript file. 

### Summary assessment
* mostly clear, but some confusing parts (e.g. useless files, things in the wrong folders)

## Documentation 
How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 

### Feedback and Comments
Not much documentation for the analysis approaches yet. 

### Summary assessment
* decently documented with some gaps

## Reproducibility
Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

### Feedback and Comments
if the analysis is reproducible, so are the most of the parts of the project.

### Summary assessment
* small parts not reproducible or required manual intervention 

## Thoroughness
How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments
Not seeing using different models yet.

### Summary assessment
* analysis not finish yet

## Further comments
_Add any other comments regarding the overall project here. Write anything you think can help your classmate improve their project._
